name = "rustarium"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-01"

[build]
command = ". \"$HOME/.cargo/env\" 2>/dev/null; cargo install worker-build && worker-build --release"

[assets]
directory = "./public"
